name: build-test-merge-publish
author: Bill Beesley <bill@beesley.dev>
description: GitHub Actions workflow to build & test npm packages
inputs:
  install-command:
    description: Command to install package dependencies
    required: false
    default: npm ci
  build-command:
    description: Command to run to build the package
    required: false
  release-command:
    description: Command to publish the package
    required: false
    default: npm run release
  main-branch:
    description: Branch to release from
    required: false
    default: 'main'
  cache-paths:
    description: Comma separated list of paths to cache
    required: false
runs:
  using: 'node12'
  pre: 'dist/pre.js'
  main: 'dist/main.js'
  post: 'dist/post.js'